### ISSUE TITLE
Link to `über-jar` is broken

### ISSUE THREAD

**Issue by sormuras** [fabiojose/snip#21]
Hi Fabio,

I am interested in trying out the "All" platform installation mode of snip.

![image](https://user-images.githubusercontent.com/2319838/162459918-8252bcf4-9837-4f0b-a4de-7d595ea87f02.png)

The link targets `https://github.com/fabiojose/snip/blob/main` - which does resolve to an `über-jar`.

Maybe @aalmiray can help to fix the @jreleaser setup?

**Comment by fabiojose** [comment]
Hi @sormuras, I'm working on this. Thank you.

**Comment by fabiojose** [comment]
jreleaser is amazing, I'm using it. But have no time yet to configure here.

**Comment by fabiojose** [comment]
Fixed.

**Comment by sormuras** [comment]
Merci - also https://github.com/fabiojose/snip/releases/latest works now as expected.
